<div class="footer">
    Generated by  {{Auth::user()->first_name}}  on {{date('Y-m-d')}} <a href="#">{{env('APP_URL')}}</a>
  </div>
<script src="//unpkg.com/xlsx/dist/xlsx.full.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
    <script>
        // function downloadCSV(csv, filename) {
        //     let csvFile = new Blob([csv], { type: "text/csv" });
        //     let downloadLink = document.createElement("a");
        //     downloadLink.download = filename;
        //     downloadLink.href = window.URL.createObjectURL(csvFile);
        //     downloadLink.style.display = "none";
        //     document.body.appendChild(downloadLink);
        //     downloadLink.click();
        // }

        // function exportTableToCSV(filename) {
        //     let csv = [];
        //     let rows = document.querySelectorAll("table tr");

        //     rows.forEach(row => {
        //         let cols = row.querySelectorAll("td, th");
        //         let rowData = [];
        //         cols.forEach(col => {
        //             let colspan = col.getAttribute('colspan');
        //             let cellText = col.innerText;
        //             rowData.push(cellText);
        //             if (colspan) {
        //                 for (let i = 1; i < colspan; i++) {
        //                     rowData.push('');
        //                 }
        //             }
        //         });
        //         csv.push(rowData.join(","));
        //     });

        //     downloadCSV(csv.join("\n"), filename);
        // }
        function exportFile(){
          var wb = XLSX.utils.table_to_book(document.querySelector('table'));
          XLSX.writeFile(wb, 'report.xlsx');
          return false;
        }

        function exportTableToPDF() {
            const { jsPDF } = window.jspdf;
            const doc = new jsPDF();
            const element = document.querySelector('table');
            const options = { background: 'white', scale: 3 };

            html2canvas(element, options).then((canvas) => {
                const imgData = canvas.toDataURL('image/PNG');
                const imgProps = doc.getImageProperties(imgData);
                const pdfWidth = doc.internal.pageSize.getWidth();
                const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
                doc.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
                doc.save('table.pdf');
            });
        }


        
    </script>